### ISSUE TITLE
Webpart disappears when trying to edit closed project

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/TrackMyTime7#90]
You can see it's still on the page: 

![image](https://user-images.githubusercontent.com/35781691/84786307-40f70400-aff5-11ea-8bb1-debc778c7618.png)

**Comment by mikezimm** [comment]
Looks like it only happens on projects in the Closed Tab.
I noticed when the webpart updated that Parking Lot and Closed was not visible.
I checked the webpart settings and disabled the Show Only Active projects.
All tabs became visible.

My guess is that that setting is also hiding the webpart.

**Comment by mikezimm** [comment]
## Here are details of error:
![image](https://user-images.githubusercontent.com/49648086/84795865-04f87a80-afc6-11ea-89fb-4c022acf1072.png)

![image](https://user-images.githubusercontent.com/49648086/84795882-088c0180-afc6-11ea-823e-d9e043dab2ff.png)

**Comment by mikezimm** [comment]
## Update, need to update all the .catch(e)

Update this function with potential new error messages:
Specifically the one for Date errors and where something like a multi-select choice (array) is null... must be empty :)

this.processCatch(e);

![image](https://user-images.githubusercontent.com/49648086/84823557-8a8f2100-afec-11ea-9793-2cc4acf31b54.png)

![image](https://user-images.githubusercontent.com/49648086/84823562-8e22a800-afec-11ea-9d28-924dffe679ed.png)

**Comment by mikezimm** [comment]
@McDKirra , I think I have the problem fixed.  I pushed to master but also updated the webpart on dev.

Since you are the master at breaking things :) can you test a few out on the live TMT site and see if this resolves the known issues?

Here's a snapshot of the ones that we know had problems (red x's)

![image](https://user-images.githubusercontent.com/49648086/84841904-b8d32780-b011-11ea-9a42-853905b545af.png)

Thanks!

**Comment by mikezimm** [comment]
@McDKirra , I am going to close this one since it seems to be fixed in the latest version in the other repo that I built today:
https://github.com/mikezimm/TrackMyTime7v2021

Thanks for all the testing!
:)
